import React from "react";
import Navbar from "@src/components/layout/Navbar";
import Head from "next/head";
import { Footer } from "@src/components/layout/Footer";

export const Layout: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  return (
    <>
      <Head>
        <title>Board game clock | newsletter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={"flex min-h-screen w-full flex-col bg-slate-900"}>
        <div
          className={
            "container mx-auto flex min-h-screen w-full flex-col bg-slate-800"
          }
        >
          <Navbar />
          <main className="flex h-full w-full flex-1 flex-col gap-12 p-4">
            {children}
          </main>
          <Footer />
        </div>
      </div>
    </>
  );
};
